services:

  database:
    image: mysql:8.0
    container_name: conteneur_mysql

    env_file:
      - .env

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

    ports:
      - "3306:3306"

    volumes:
      - db_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  node-app:
    build: .
    container_name: node_app
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "3000:3000"

volumes:
  db_data:
